spring.application.name=demo
server.port=8080
<<<<<<< HEAD
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=student_management;encrypt=false;trustServerCertificate=true
=======
spring.thymeleaf.prefix=classpath:/
spring.thymeleaf.suffix=.html
# spring.datasource.url=jdbc:sqlserver://DESKTOP-R8J6D5M\\MSSQLSERVER1:1433;encrypt=true;trustServerCertificate=true;databaseName=schoolmanager
# spring.datasource.username=sa
# spring.datasource.password=123123

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLyPhongHoc-PhongHoc;encrypt=true;trustServerCertificate=true
>>>>>>> a7aa5184c3e69cc70efb3a4d2db08b4d6c09b33d
spring.datasource.username=sa
spring.datasource.password=123456Aa

# spring.datasource.url=jdbc:sqlserver://den1.mssql7.gear.host:1433;encrypt=true;trustServerCertificate=true;databaseName=school123456
# spring.datasource.username=school123456
# spring.datasource.password=Tf1XN700~Y!T
spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=truespring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
